spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver
server.port=8080
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ===================================================================
# JWT CONFIGURATION
# ===================================================================
# A secure, base64-encoded secret key for signing JWTs.
# IMPORTANT: This is an example key. In a real production environment, you should generate your own
# strong, random key and preferably load it from an environment variable or a secret manager.
# You can generate a key online or using a tool like: echo -n 'a_very_long_and_secure_secret_for_your_app' | base64


application.security.jwt.secret-key=Q2hhbmdlVGhpc0tleVRvQXRSYW5kb21TdHJvbmdLZXlUaGF0SXNNb3JlVGhhbkF0MjU2Yml0cw==


finnhub.api.key=d8sn1fpr01qh5resllvgd8sn1fpr01qh5reslm00

influxdb.url=http://localhost:8086

# The secret API token that grants write access to the database.
# Treat this like a password and never commit it to a public repository.
influxdb.token=ncUqQsEyd0u2NeWfA_ms9D8xGNJtbXBsmTWmJxVwCyUjszpwxmBLOwIfch9TAW5QqiD_8r9zC4Duwc09vlJJcA==

# The name of the organization created during the InfluxDB setup.
influxdb.org=tradingapp-org

# The name of the bucket where stock price data points will be stored.
influxdb.bucket=stock-prices
# highlight-end

